### ISSUE TITLE
updating offical-images, tag for 3.1.2?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker#114]
I see we've bumped r-base to 3.1.3 and that the Dockerfile no longer builds with 3.1.2.  Nice, only...

I guess this means that we need to PR the official-images again, as that build will presumably now be broken (recall it is locked pointing to a specific hash of the Dockerfile in our repo, so it doesn't reflect the change) and thus the security updates it inherits when the Debian base image updates will no longer be propagating through r-base and the rest of our images (since r-base will continue to point to the last successful build).  

@eddelbuettel guessing you're not gonna like this, but I'm guessing when we next send a PR to official-images, they're going to want us to point to a separate Dockerfile for 3.1.2; just like almost all other official images do.  Normally we wouldn't have to change anything, because that tag would still point to the old hash with the Dockerfile recipe for building 3.1.2, but of course that doesn't work as it is broken.  

Note that they already have us define the tag '3.1.2' for the official r-base, so people may have dockerfiles that build with `FROM r-base:3.1.2` out there; so I'm not sure we can simply convince them that nothing other than 'latest' should ever exist...

**Comment by eddelbuettel** [comment]
Hm.  The question is if we should indeed PR for every 'official' R release.  As we aim to be _the_ container for R, we probably should.

OTOH R 3.2.0 is also pretty close with a release of April 16.  So shall we plan two PR dances, or just one?   Part of me thinks two as a release is a release, part of me thinks we should be pragmatic with the Docker folks. 

Re the tags for '3.1.2':  wasn't part of the reason for tags that they will work even if the corresponding version is no longer HEAD?

**Comment by cboettig** [comment]
If the current r-base wasn't broken and didn't fail to build, then sure, I wouldn't necessarily think we had to do a PR at this point.  Right, the tags don't care what is at HEAD, but the problem is that the old version that used to work is broken now, and simply cannot build R 3.1.2.  I'm not quite sure why it is failing to build, but I think you've already seen the error message here: https://registry.hub.docker.com/u/rocker/r-base/build_id/20027/code/bcvt28cauvgciiwvllg9unw/

If you go to the official image, https://registry.hub.docker.com/_/r-base/, and click on the Dockerfile that it links to, you get https://github.com/rocker-org/rocker/blob/fa244c6a6010d41fca568d2469be681959a1f3c4/r-base/Dockerfile, and if I try to build that, I get the same error:

```
E: Version '3.1.2*' for 'r-base' was not found
E: Version '3.1.2*' for 'r-base-dev' was not found
E: Version '3.1.2*' for 'r-recommended' was not found
```

Any idea why this is happening?  I thought this was supposed to keep working even when R was upgraded.  Is this a problem with the apt-pinning or something?

If we can get this fixed upstream so that the image still builds then we're in great shape.  I'm just concerned that at present none of our images will automatically be getting the debian security updates because they cannot be rebuilt when the debian image is updated...

**Comment by eddelbuettel** [comment]
Debian unstable only keeps one version,  so now it is 3.1.3.

I fixed this as soon as I saw the failure. If I recall it did build subsequently.

**Comment by cboettig** [comment]
Yes,I saw your fix, but that doesn't fix it in official images, which
points to a fixed version and can only be fixed by PR, hence my comments
here

**Comment by eddelbuettel** [comment]
Right right right -- for that we do need (and maybe _want_) a PR as 3.1.3 is after all meant to be the final 3.1.* series version.

**Comment by cboettig** [comment]
Yup. And until we do the PR the existing r-base:latest can't build.  So
what do we do about the 3.1.2 tag? We can't just leave it as it is because
it no longer builds. I guess we would be fine if it was 3.1.1 we wanted,
since that's what's in Jessie.  Is there a repo we can add so that 3.1.2
can still build?

**Comment by eddelbuettel** [comment]
I don't think so/not easily. There is archive.debian.net (or .org) but it is _not_ of the same reliability.

In all honesty, "buildability" of Rocker/r-base broke the moment I sent R 3.1.3 to Debian -- replacing 3.1.2

**Comment by cboettig** [comment]
yeah, I was afraid that was the answer.  or build from source I suppose.
We can try and send a PR that simply deprecates the 3.1.2 tag, but I have a
feeling they won't like that. I have a feeling they will tell us that this
is why they wanted things built from Jessie in the first place (not saying
that makes sense, since clearly we want the latest R and not something
locked several versions behind)

**Comment by eddelbuettel** [comment]
Maybe I am missing something but doesn't the tag at hub.docker.com stay?  

```{.sh}
edd@max:~$ docker images|grep 6.0
debian                       6.0                   3af93ba75125        8 weeks ago         76.61 MB
debian                       6.0.10                3af93ba75125        8 weeks ago         76.61 MB
debian                       6.0.9                 fee2ea4e24af        7 months ago        78.48 MB
debian                       6.0.8                 d56191e18d6b        13 months ago       113.1 MB
edd@max:~$ 
```

That looks like three distinct versions of Debian 6.0 to me -- with 6.0 aliases to the 6.0.10 which was most recent when I pulled this last (weeks ago).

Can't we do the same?

**Comment by cboettig** [comment]
You mean, leave the tag pointing to a Dockerfile that can't be built any
more?  Sure, we can leave the tag, that would be the normal approach, but
normally that dockerfile at that tag would still build successfully.  As
I've been trying to say all along, the tag in our case point to a broken
dockerfile.  If the image was never rebuilt with security patches, then
sure, it would still stuck around, but that seems bad... Am I missing
something?

**Comment by eddelbuettel** [comment]
Probably me who is confused. I am thinking of the 'tags' as pointing to containers, so latest has now a need for an updated 3.1.3 tag pointed to the new hash key of the new cointainer.

I was (maybe naively and falsely) thinking that the 3.1.2 tag would still point to the same hashed container we built when 3.1.2 came out / when we built it.

**Comment by cboettig** [comment]
Aha, I see where you're coming from now.  If tags pointed to a container
hash that would indeed be the case, but such a container would also then
not be getting security updates etc.

Instead, the point to a *git commit hash* in our Github repo, such as
https://github.com/rocker-org/official-images/blob/master/library/r-base#L5
(yeah, so docker also uses the term tag to refer to the base name attached
to a container hash, so it's confusing I agree).  If you check out the
official images on the hub, you'll see they are rebuilt periodically.
Because this runs all the apt-get install commands again, this means that
they pull the latest versions (unless version pinned) of software as they
update, and hence (I suppose the thinking is) they get any key security
patches.  Since the base images are also rebuilt in this manner, they also
inherit updates added to the base image at this time.  so you can see
https://registry.hub.docker.com/_/r-base/ was last built only 2 days ago,
even though it was built when we did our our original PR.  Only the image
can't update if the that build fails.

Am I making any sense?

**Comment by eddelbuettel** [comment]
Yes. :)

But we then cannot hard-wire versions (ie the 3.1.2) which makes the Docker folks cry because they want fixed version number.  Rock, meet hard place,

**Comment by cboettig** [comment]
Looks like we're in the clear :P

**Comment by eddelbuettel** [comment]
Seems like it hasn't built yet though.

**Comment by cboettig** [comment]
If you pull r-base (not rocker/r-base) it seems to have R 3.1.3 now so I
think it is built...

**Comment by eddelbuettel** [comment]
Indeed, and very nice.  What difference four hours can make :)

**Comment by cboettig** [comment]
But that's been true for a few days, so I don't think it just went up

**Comment by eddelbuettel** [comment]
Maybe I was under-caffeinated and fell once again for rocker != r-base, but I meant to pull r-base.
