### ISSUE TITLE
rocker/rstudio does not have userconf.sh

### ISSUE THREAD

**Issue by SemanticBeeng** [rocker-org/rocker#269]
Hi,

This wiki page mentions the use of `userconf.sh` but there is no such script in the `rocker/rstudio` container.

https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine#interactive-containers

```
root@bb062398355b:/# userconf.sh
bash: userconf.sh: command not found
```
Tried to make `userconf.sh` from https://github.com/rocker-org/rocker/blob/master/rstudio/testing/userconf.sh in a mounted directory and run it from there

```
.../rstudio# ./userconf.sh 
s6-envdir: fatal: unable to envdir: No such file or directory
```

`rstudio` itself runs fine but my goal is to run R interactively with my own $USER/$USERID and share it outside to access from Intellij.
Please advise what I am missing?

Thanks
Nick

**Comment by cboettig** [comment]
https://github.com/rocker-org/rocker-versioned/tree/master/rstudio

**Comment by 4current** [comment]
Perhaps this is the problem you are facing which is not addressed in enough detail in the documentation. When you provide a path to the docker daemon for volume mount with -v. If the path is not present on the host, it gets auto-created with root ownership. However, is you specify a directory already created with your UID, then ownership is retained. After that rstudio, inside the container, will use the value passed with -e USERID=$UID. So
`mkdir $HOME/Projects/rstudio
docker run -d -p8787:8787 -v $HOME/Projects/rstudio:/home/rstudio/Projects -e USERID=$UID rocker/rstudio
`

**Comment by SemanticBeeng** [comment]
Still having this issue

```
root@e61bf052db42:/home/rstudio# /usr/bin/with-contenv 
s6-envdir: fatal: unable to envdir: No such file or directory
```

Did careful research in all the material could find and could not find an explanation for this.
Seems to be something wrong with `s6`.

Do you know why this happens and I am missing the point somehow?

**Comment by cboettig** [comment]
@SemanticBeeng Thanks for your interest in the project.  From your report above, it is really not clear what you are trying to do or how to reproduce the errors that you see, so it is difficult to help you troubleshoot.  The title issue asked where to find the sources for the `userconf.sh` script, which are not in this repository at all, but live in the `rocker-versioned` repo I linked above.

You'll see in the Dockerfile linked there that userconf.sh is copied onto the image as `/etc/cont-init.d/userconf` https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/Dockerfile#L74 , so if you wanted to modify the sources you modify `userconf.sh`, but on the container the file is `/etc/cont-init.d/userconf`.  Also note that this file is called by S6 automatically on startup (i.e. the default command, `/init`, which will call S6 and run all 
 the init processes just fine).  You aren't really intended to run bits of the init script manually in a running container.  Of course it is just a bash script and you can run `bash /etc/cont-init.d/userconf` if you really want to.  HTH

**Comment by SemanticBeeng** [comment]
Thanks for reply.
Trying to execute exactly this https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine#interactive-containers

Should I simply do this with the `rocker-version` image instead?
Will re-evaluate based on your details. Thanks again, Carl.

**Comment by cboettig** [comment]
@SemanticBeeng Ah, so you're trying to share files with Linux-based local host with a user ID other than `1000` when using the `rstudio` container in terminal mode (i.e. not using rstudio)?  

(If you're trying to share files with a host on Mac, or with a host on linux with UID=1000 none of that is necessary.  If you want to use rstudio, which I imagine is why you are using the `rstudio` container, you just need to set the environmental variable `$UID` like it says, no need to call userconf manually).  

If you need to use the rstudio container in bash mode for some reason (i.e. you don't want to actually use the rstudio interface), then you are correct that you need to run userconf manually, and I see those directions were outdated, I've just updated them:  https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine/_compare/dd376cf348947b4fea0391abece701b330fc47fb

**Comment by cboettig** [comment]
p.s. re using https://github.com/rocker-org/rocker-versioned/tree/master/rstudio, you *are already using* rocker-versioned, it isn't an image, it's a collection of images (almost all our github repos contain multiple docker images, see: https://www.rocker-project.org/images/)  This github repo (rocker-org/rocker) hosts base images

**Comment by SemanticBeeng** [comment]
Okay, thanks for updating instructions.

Trying to use `rstudio` _and_ start a bash shell to update OS with some packages and then run R session in command line to execute tests.

Installing `syberia` and using container for development.

Will try the params combinations you described. 
Many thanks.

**Comment by cboettig** [comment]
cool. 

 For doing updates I recommend launching with the default command and then using `docker exec` to enter the container in a root shell for making updates & any other sys-admin stuff.  

Alternately you can just set `-e root=TRUE` when launching the container and use the nice new terminal embedded inside RStudio for these tasks.

**Comment by SemanticBeeng** [comment]
Have already been able to deploy `syberia`  with a container ran without volume sharing and the rest above.
That part worked nice and smooth.
Now hope to make volume sharing seamless for a sustainable developer experience.

**Comment by cboettig** [comment]
nice. :+1:.  re-open if you need anything
